import { type Language } from "@/lib/forge/models";

export const labels = {
  en: {
    today: "Today",
    food: "Food",
    progress: "Progress",
    more: "More",
    setupTitle: "Set up your baseline",
    setupCopy:
      "Enter your profile and starting weight before using the dashboard.",
    finishSetup: "Finish setup",
    calorieTarget: "Target",
    consumed: "Consumed",
    remaining: "Remaining",
    quickAdd: "Quick add",
    recentEntries: "Logged today",
    emptyEntries: "No food logged yet.",
    activityProfile: "Activity profile",
    averageDailySteps: "Average daily steps",
    gymSessionsPerWeek: "Gym sessions / week",
    typicalGymDuration: "Typical gym duration",
    otherRegularActivity: "Other regular activity",
    otherActivitySessionsPerWeek: "Other activity sessions / week",
    otherActivityDuration: "Other activity duration (min)",
    wasTodayDifferent: "Was today different?",
    lessActive: "Less active than usual",
    normalActivity: "Normal",
    moreActive: "More active than usual",
    activityToday: "Activity today",
    gymToday: "Gym today?",
    yes: "Yes",
    no: "No",
    estimatedExpenditure: "Estimated expenditure",
    basedOnNormalActivity: "Based on your normal activity profile.",
    doneForToday: "Done for today?",
    todayCompleted: "Today completed ✓",
    finishToday: "Finish today",
    todaysSteps: "Today's steps",
    todaysActivity: "Today's activity",
    todaysWeight: "Today's weight",
    addWeightNow: "Add weight",
    saveWeight: "Save weight",
    saveWeightPrompt: "Save today's weight as",
    confirmWeight: "Confirm",
    confirmDay: "Confirm day",
    confirmChange: "Confirm change",
    cancel: "Cancel",
    recordedToday: "Recorded today.",
    normalActivityShort: "Normal activity",
    todayEstimate: "Estimated expenditure",
    activityExplanation:
      "Your estimated daily expenditure is calculated from your BMR and normal activity profile. As more calorie and weight data accumulates, FORGE compares the estimate against your real-world trend and adjusts it.",
    foodSearch: "Search foods",
    search: "Search",
    addToToday: "Add to today",
    remove: "Remove",
    saveFood: "Save food",
    savedFoods: "Saved foods",
    customFood: "Custom food",
    meals: "Meals",
    buildMeal: "Build meal",
    saveMeal: "Save meal",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    steps: "Steps",
    gym: "Gym",
    duration: "Gym min",
    extraActivity: "Extra min",
    deficitOrSurplus: "Balance",
    activityBurn: "Activity burn",
    currentWeight: "Current",
    startWeight: "Starting",
    targetWeight: "Target",
    totalChange: "Change",
    estimatedTime: "ETA",
    averageWeeklyChange: "Weekly trend",
    bodyweightTrend: "Bodyweight trend",
    adaptiveTdee: "Adaptive TDEE",
    basedOn: "Based on",
    confidence: "Confidence",
    insights: "Insights",
    noData: "Add more data to unlock this estimate.",
    profile: "Profile",
    settings: "Settings",
    english: "English",
    finnish: "Finnish",
    goalType: "Goal",
    maintenance: "Maintenance",
    loss: "Loss",
    gain: "Gain",
    manualCalories: "Manual calories",
    weeklyRate: "Weekly rate",
    height: "Height (cm)",
    age: "Age",
    sex: "Sex",
    male: "Male",
    female: "Female",
    name: "Name",
    save: "Save",
    addWeight: "Add weight",
    noteFineli: "Fineli results are cached locally when available.",
    fineliFallback:
      "Live Fineli results are unavailable right now. Saved foods still work offline.",
    fineliChooseFood: "Choose a food from the results list to preview nutrition and add it to today.",
    mealName: "Meal name",
    open: "Open",
    hide: "Hide",
    firstWeight: "Starting weight (kg)",
    todayFocus: "Today",
    done: "Done",
    planned: "Planned",
    usual: "usual",
  },
  fi: {
    today: "Tänään",
    food: "Ruoka",
    progress: "Edistyminen",
    more: "Lisää",
    setupTitle: "Aseta lähtötiedot",
    setupCopy: "Syötä profiili ja aloituspaino ennen dashboardin käyttöä.",
    finishSetup: "Tallenna tiedot",
    calorieTarget: "Tavoite",
    consumed: "Syöty",
    remaining: "Jäljellä",
    quickAdd: "Pikalisäys",
    recentEntries: "Merkinnät tänään",
    emptyEntries: "Ruokia ei ole vielä kirjattu.",
    activityProfile: "Aktiviteettiprofiili",
    averageDailySteps: "Keskimääräiset askeleet / päivä",
    gymSessionsPerWeek: "Salikerrat / viikko",
    typicalGymDuration: "Tavallinen salikerta (min)",
    otherRegularActivity: "Muu säännöllinen aktiivisuus",
    otherActivitySessionsPerWeek: "Muun aktiviteetin kerrat / viikko",
    otherActivityDuration: "Muu aktiviteetti (min)",
    wasTodayDifferent: "Poikkesiko tämä päivä tavallisuudesta?",
    lessActive: "Vähemmän aktiivinen kuin normaalisti",
    normalActivity: "Normaali",
    moreActive: "Aktiivisempi kuin normaalisti",
    activityToday: "Aktiivisuus tänään",
    gymToday: "Onko sali tänään?",
    yes: "Kyllä",
    no: "Ei",
    estimatedExpenditure: "Arvioitu kulutus",
    basedOnNormalActivity: "Perustuu normaalin aktiivisuusprofiilin mukaan.",
    doneForToday: "Valmista tälle päivälle?",
    todayCompleted: "Päivä valmis ✓",
    finishToday: "Viimeistele päivä",
    todaysSteps: "Tämän päivän askeleet",
    todaysActivity: "Tämän päivän aktiivisuus",
    todaysWeight: "Tämän päivän paino",
    addWeightNow: "Lisää paino",
    saveWeight: "Tallenna paino",
    saveWeightPrompt: "Tallenna tämän päivän paino",
    confirmWeight: "Vahvista",
    confirmDay: "Vahvista päivä",
    confirmChange: "Vahvista muutos",
    cancel: "Peruuta",
    recordedToday: "Kirjattu tänään.",
    normalActivityShort: "Normaali aktiivisuus",
    todayEstimate: "Arvioitu kulutus",
    activityExplanation:
      "Arvioitu päivittäinen kulutus lasketaan BMR:n ja normaalin aktiviteettiprofiilin pohjalta. Kun syötyt kalorit ja paino dataa kertyy, FORGE vertaa arviota todelliseen painon kehitykseen ja säätää arvioita.",
    foodSearch: "Hae ruokia",
    search: "Hae",
    addToToday: "Lisää tälle päivälle",
    remove: "Poista",
    saveFood: "Tallenna ruoka",
    savedFoods: "Tallennetut ruoat",
    customFood: "Oma ruoka",
    meals: "Ateriat",
    buildMeal: "Rakenna ateria",
    saveMeal: "Tallenna ateria",
    calories: "Kalorit",
    protein: "Proteiini",
    carbs: "Hiilarit",
    fat: "Rasva",
    steps: "Askeleet",
    gym: "Sali",
    duration: "Salimin",
    extraActivity: "Lisämin",
    deficitOrSurplus: "Tase",
    activityBurn: "Aktiivisuus",
    currentWeight: "Nykyinen",
    startWeight: "Aloitus",
    targetWeight: "Tavoite",
    totalChange: "Muutos",
    estimatedTime: "Arvio",
    averageWeeklyChange: "Viikkotrendi",
    bodyweightTrend: "Painotrendi",
    adaptiveTdee: "Mukautuva TDEE",
    basedOn: "Perustuu",
    confidence: "Luottamus",
    insights: "Huomiot",
    noData: "Lisää dataa saadaksesi arvion.",
    profile: "Profiili",
    settings: "Asetukset",
    english: "Englanti",
    finnish: "Suomi",
    goalType: "Tavoite",
    maintenance: "Ylläpito",
    loss: "Pudotus",
    gain: "Nousu",
    manualCalories: "Manuaaliset kalorit",
    weeklyRate: "Viikkotahti",
    height: "Pituus (cm)",
    age: "Ikä",
    sex: "Sukupuoli",
    male: "Mies",
    female: "Nainen",
    name: "Nimi",
    save: "Tallenna",
    addWeight: "Lisää paino",
    noteFineli: "Fineli-tulokset tallennetaan paikallisesti kun niitä saadaan.",
    fineliFallback:
      "Finelin livetuloksia ei saatu juuri nyt. Tallennetut ruoat toimivat silti offline-tilassa.",
    mealName: "Aterian nimi",
    fineliChooseFood: "Valitse ruoka hakutuloksista nähdäksesi ravintosisällön ja lisätäksesi sen tälle päivälle.",
    open: "Avaa",
    hide: "Piilota",
    firstWeight: "Aloituspaino (kg)",
    todayFocus: "Tänään",
    done: "Tehty",
    planned: "Suunniteltu",
    usual: "tavallinen",
  },
} as const;

export type Copy = (typeof labels)[Language];
